### ISSUE TITLE
Can't deploy on Portainer

### ISSUE THREAD

**Issue by khalidrehan** [pe3zx/mthc#14]
Hi,
I liked your idea here, and I'm trying to deploy it on Portainer 2.0.1, but failing.
Errors about the network configuration and about other services:

`The network mithc1_mthc cannot be used with services. Only networks scoped to the swarm can be used, such as those created with the overlay driver. `

I'm lost, and I hope if can guide me.
I have installed MISP using https://github.com/harvard-itsecurity/docker-misp, but for I'm not experienced with Dockers much, I could not combine the other solutions (Cortex, TheHive) easily.

Regards,
Khalid.

**Comment by pe3zx** [comment]
Hi @khalidrehan,

I don't familiar with Portainer nor swarm, but the error message leads me to the fact that you might need to create the `mthc_mthc` in swarm mode, not local scope.

Because it's still impossible to [specify network scope in compose file](https://github.com/docker/cli/issues/410), some recommendation has mentioned about creating the network manually with `docker network create` first, and specify `external: true` on the compose file.

Hope this helps.
